name: ToolKit
main: org.mcdynasty.toolkit.ToolKit
version: 0.1
load: STARTUP
loadbefore: [Essentials]
author: psgs, PixelCrumbs
description: ToolKit is a lightweight plugin designed to execute simple commands.
depend: [WorldEdit]